class UFloat:
    def __init__(self, value: float, uncertainty: float) -> None: ...
    def __add__(self, other: UFloat | float) -> UFloat: ...
    def __radd__(self, other: UFloat | float) -> UFloat: ...
    def __sub__(self, other: UFloat | float) -> UFloat: ...
    def __rsub__(self, other: UFloat | float) -> UFloat: ...
    def __mul__(self, other: UFloat | float) -> UFloat: ...
    def __rmul__(self, other: UFloat | float) -> UFloat: ...
    def __truediv__(self, other: UFloat | float) -> UFloat: ...
    def __rtruediv__(self, other: UFloat | float) -> UFloat: ...
    def __neg__(self) -> UFloat: ...
    def __pos__(self) -> UFloat: ...
    def __abs__(self) -> UFloat: ...
    def __pow__(self, other: UFloat | float) -> UFloat: ...
    def __rpow__(self, other: UFloat | float) -> UFloat: ...
    @property
    def nominal_value(self) -> float: ...
    @property
    def std_dev(self) -> float: ...
    n: float
    s: float

def ufloat(value: float, uncertainty: float, tag: str = ...) -> UFloat: ...
