from typing import Any

def __getattr__(name: str) -> Any: ...  # module-level dynamic attrs

class _VPythonObject:
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

def vector(x, y, z) -> float: ...
def rate(frequency: float) -> None: ...
def mag(v) -> float: ...
def sin(v) -> float: ...
def cos(v) -> float: ...
def norm(v) -> ...: ...
def dot(a, b) -> float: ...
def cross(a, b) -> ...: ...

pi: float
e: float

class color:
    red: ...
    green: ...
    blue: ...
    white: ...
    black: ...
    yellow: ...
    orange: ...
    cyan: ...
    magenta: ...
    purple: ...
    gray: ...
class sphere(_VPythonObject):
    def __init__(self,**kwargs: Any) -> None: ...
class box(_VPythonObject):
    def __init__(self,**kwargs: Any) -> None: ...
class cylinder(_VPythonObject):
    def __init__(self,**kwargs: Any) -> None: ...
class cone(_VPythonObject):
    def __init__(self,**kwargs: Any) -> None: ...
class arrow(_VPythonObject):
    def __init__(self,**kwargs: Any) -> None: ...
class helix(_VPythonObject):
    def __init__(self,**kwargs: Any) -> None: ...
class ring(_VPythonObject):
    def __init__(self,**kwargs: Any) -> None: ...
class ellipsoid(_VPythonObject):
    def __init__(self,**kwargs: Any) -> None: ...
